UA363: Add managing fallback image for product in Sitecore
epam/sitecore-headless-commerce-accelerator pull request #232
Opened 2020-05-29 13:37 UTC by yuya-yuliya

- add Site Settings Provider
- add ImageFallbackContextProcessor

2020-06-01 15:01 UTC, evgenii-nikulin approved these changes

2020-06-02 09:05 UTC, ghost requested changes

2020-06-02 09:05 UTC, larionovadaria commented on src/Foundation/Base/code/HCA.Foundation.Base.csproj
> +    <ProjectReference Include="..\..\ReactJss\code\HCA.Foundation.ReactJss.csproj">
Now you can't use, for example, logging service in `HCA.Foundation.ReactJss`. Remove this dependency and find a better place for processor.

2020-06-02 09:05 UTC, larionovadaria commented on src/Foundation/Base/code/packages.config
> +  <package id="Sitecore.JavaScriptServices.Configuration" version="14.0.0" targetFramework="net471" />
To remove

2020-06-02 09:24 UTC, yuya-yuliya commented on src/Feature/Catalog/code/Pipelines/GetLayoutServiceContext/ProductColorsContextExtension.cs
> +            // TODO: Refactor. Use SiteSettingsProvider
For this TODO created US

2020-06-02 14:08 UTC, merged